### ISSUE TITLE
Examples missing?

### ISSUE THREAD

**Issue by StephenTallamy** [mrin9/RapiPdf#6]
When rendering out the PDF I seem to only get the model data from my OpenAPI v3 document. I'm not seeing the examples. Any reason why no examples shown?

**Comment by mrin9** [comment]
the only reason is that we couldn't reach any consensus within our team to implement it and the way to display it. 

Are you looking for curl command, code snippet or just some sample values based on data-types ?
If you can provide me some samples based on your needs covering most possible data-types and scenarios then i can re-open this discussion

**Comment by HolisticDeveloper** [comment]
Let's say we have the following schema defined:
```yaml
components:
    schemas:
        rider:
            type: object
            description: A registered rider.
            properties:
                id:
                    type: integer
                    format: int64
                    description: The external rider id.
                    example: 12345
                lastName:
                    type: string
                    example: Pan
                firstName:
                    type: string
                    example: Peter
            required:
                - id
                - lastName
            example:
                id: 12345
                lastName: Pan
```

It would be helpful to show the example for each individual property as well as the example for the entire schema. Note that the example for the schema might not include non-required properties.
